//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf.Fields.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Golf.Fields.Database.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string DbConnectionCouldNotBeEstablished
        {
            get
            {
                return ResourceManager.GetString("DbConnectionCouldNotBeEstablished", resourceCulture);
            }
        }

        public static string DbSettingsHasNotBeenProvided
        {
            get
            {
                return ResourceManager.GetString("DbSettingsHasNotBeenProvided", resourceCulture);
            }
        }


        public static string InvalidApplicationCustomSettings
        {
            get
            {
                return ResourceManager.GetString("InvalidApplicationCustomSettings", resourceCulture);
            }
        }



        public static string TcpConnectionCouldNotBeEstablished
        {
            get
            {
                return ResourceManager.GetString("TcpConnectionCouldNotBeEstablished", resourceCulture);
            }
        }


        public static string TcpSettingsHasNotBeenProvided
        {
            get
            {
                return ResourceManager.GetString("TcpSettingsHasNotBeenProvided", resourceCulture);
            }
        }


        public static string ErrorReadingTcpResponse
        {
            get
            {
                return ResourceManager.GetString("ErrorReadingTcpResponse", resourceCulture);
            }
        }


        public static string DataWasNotReceivedOverTcp
        {
            get
            {
                return ResourceManager.GetString("DataWasNotReceivedOverTcp", resourceCulture);
            }
        }

        public static string SuccessfullyUpdatedToVersion
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyUpdatedToVersion", resourceCulture);
            }
        }


        public static string FailedUpgradeToVersion
        {
            get
            {
                return ResourceManager.GetString("FailedUpgradeToVersion", resourceCulture);
            }
        }


        public static string SuccessfullySeededBatch
        {
            get
            {
                return ResourceManager.GetString("SuccessfullySeededBatch", resourceCulture);
            }
        }


        public static string DatabaseSettingNotFound
        {
            get
            {
                return ResourceManager.GetString("DatabaseSettingNotFound", resourceCulture);
            }
        }


        public static string TcpConnectionSettingNotFound
        {
            get
            {
                return ResourceManager.GetString("TcpConnectionSettingNotFound", resourceCulture);
            }
        }
    }
}
